# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tool_sandbox_pb2 as tool__sandbox__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tool_sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToolExecutorServiceStub:
    """工具执行服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/yuanbot.sandbox.ToolExecutorService/Execute',
                request_serializer=tool__sandbox__pb2.ToolRequest.SerializeToString,
                response_deserializer=tool__sandbox__pb2.ToolResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/yuanbot.sandbox.ToolExecutorService/ListTools',
                request_serializer=tool__sandbox__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=tool__sandbox__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/yuanbot.sandbox.ToolExecutorService/HealthCheck',
                request_serializer=tool__sandbox__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=tool__sandbox__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ToolExecutorServiceServicer:
    """工具执行服务
    """

    def Execute(self, request, context):
        """执行工具
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """列出可用工具
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=tool__sandbox__pb2.ToolRequest.FromString,
                    response_serializer=tool__sandbox__pb2.ToolResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=tool__sandbox__pb2.ListToolsRequest.FromString,
                    response_serializer=tool__sandbox__pb2.ListToolsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=tool__sandbox__pb2.HealthCheckRequest.FromString,
                    response_serializer=tool__sandbox__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yuanbot.sandbox.ToolExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yuanbot.sandbox.ToolExecutorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolExecutorService:
    """工具执行服务
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yuanbot.sandbox.ToolExecutorService/Execute',
            tool__sandbox__pb2.ToolRequest.SerializeToString,
            tool__sandbox__pb2.ToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yuanbot.sandbox.ToolExecutorService/ListTools',
            tool__sandbox__pb2.ListToolsRequest.SerializeToString,
            tool__sandbox__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yuanbot.sandbox.ToolExecutorService/HealthCheck',
            tool__sandbox__pb2.HealthCheckRequest.SerializeToString,
            tool__sandbox__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
