# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tool_sandbox.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'tool_sandbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12tool_sandbox.proto\x12\x0fyuanbot.sandbox\"w\n\x0bToolRequest\x12\x0f\n\x07tool_id\x18\x01 \x01(\t\x12\x13\n\x0bparams_json\x18\x02 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x03 \x01(\x05\x12\x15\n\rinvocation_id\x18\x04 \x01(\t\x12\x12\n\nauth_token\x18\x05 \x01(\t\"\xa7\x01\n\x0cToolResponse\x12\x15\n\rinvocation_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0boutput_json\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x05 \x01(\x03\x12\x30\n\x0bstatus_code\x18\x06 \x01(\x0e\x32\x1b.yuanbot.sandbox.StatusCode\"\x8e\x01\n\x08ToolInfo\x12\x0f\n\x07tool_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x1a\n\x12params_schema_json\x18\x04 \x01(\t\x12\x32\n\x0csandbox_type\x18\x05 \x01(\x0e\x32\x1c.yuanbot.sandbox.SandboxType\" \n\x10ListToolsRequest\x12\x0c\n\x04tags\x18\x01 \x03(\t\"=\n\x11ListToolsResponse\x12(\n\x05tools\x18\x01 \x03(\x0b\x32\x19.yuanbot.sandbox.ToolInfo\"\x14\n\x12HealthCheckRequest\"R\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x19\n\x11\x61\x63tive_executions\x18\x03 \x01(\x05*\x88\x01\n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\x12\n\x0eTOOL_NOT_FOUND\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x02\x12\x15\n\x11PERMISSION_DENIED\x10\x03\x12\x13\n\x0f\x45XECUTION_ERROR\x10\x04\x12\x11\n\rSANDBOX_ERROR\x10\x05\x12\x12\n\x0eINVALID_PARAMS\x10\x06*:\n\x0bSandboxType\x12\x0b\n\x07PROCESS\x10\x00\x12\n\n\x06\x44OCKER\x10\x01\x12\x08\n\x04WASM\x10\x02\x12\x08\n\x04GRPC\x10\x03\x32\x8b\x02\n\x13ToolExecutorService\x12\x46\n\x07\x45xecute\x12\x1c.yuanbot.sandbox.ToolRequest\x1a\x1d.yuanbot.sandbox.ToolResponse\x12R\n\tListTools\x12!.yuanbot.sandbox.ListToolsRequest\x1a\".yuanbot.sandbox.ListToolsResponse\x12X\n\x0bHealthCheck\x12#.yuanbot.sandbox.HealthCheckRequest\x1a$.yuanbot.sandbox.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tool_sandbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSCODE']._serialized_start=679
  _globals['_STATUSCODE']._serialized_end=815
  _globals['_SANDBOXTYPE']._serialized_start=817
  _globals['_SANDBOXTYPE']._serialized_end=875
  _globals['_TOOLREQUEST']._serialized_start=39
  _globals['_TOOLREQUEST']._serialized_end=158
  _globals['_TOOLRESPONSE']._serialized_start=161
  _globals['_TOOLRESPONSE']._serialized_end=328
  _globals['_TOOLINFO']._serialized_start=331
  _globals['_TOOLINFO']._serialized_end=473
  _globals['_LISTTOOLSREQUEST']._serialized_start=475
  _globals['_LISTTOOLSREQUEST']._serialized_end=507
  _globals['_LISTTOOLSRESPONSE']._serialized_start=509
  _globals['_LISTTOOLSRESPONSE']._serialized_end=570
  _globals['_HEALTHCHECKREQUEST']._serialized_start=572
  _globals['_HEALTHCHECKREQUEST']._serialized_end=592
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=594
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=676
  _globals['_TOOLEXECUTORSERVICE']._serialized_start=878
  _globals['_TOOLEXECUTORSERVICE']._serialized_end=1145
# @@protoc_insertion_point(module_scope)
